<?php

use yii\db\Schema;
use yii\db\Migration;

class m150705_213801_create_city_table extends Migration
{
    public function up()
    {
        $tableOptions = null;
        $this->createTable(
            'ref_city', 
            [
                'id' => Schema::TYPE_PK,
                'province_id' => Schema::TYPE_INTEGER .' NOT NULL',
                'name' => Schema::TYPE_STRING . '(200) NOT NULL',
                'description' => Schema::TYPE_TEXT. ' NULL',
                'created_at' => Schema::TYPE_DATETIME . ' NULL',
                'updated_at' => Schema::TYPE_DATETIME . ' NULL',
                'created_by' => Schema::TYPE_INTEGER . ' NULL',
                'updated_by' => Schema::TYPE_INTEGER . ' NULL',
            ], $tableOptions
        );
        
        $this->insert('ref_city', ['id'=>1101, 'province_id'=>11, 'name'=>'Simeulue']);
        $this->insert('ref_city', ['id'=>1102, 'province_id'=>11, 'name'=>'Aceh Singkil']);
        $this->insert('ref_city', ['id'=>1103, 'province_id'=>11, 'name'=>'Aceh Selatan']);
        $this->insert('ref_city', ['id'=>1104, 'province_id'=>11, 'name'=>'Aceh Tenggara']);
        $this->insert('ref_city', ['id'=>1105, 'province_id'=>11, 'name'=>'Aceh Timur']);
        $this->insert('ref_city', ['id'=>1106, 'province_id'=>11, 'name'=>'Aceh Tengah']);
        $this->insert('ref_city', ['id'=>1107, 'province_id'=>11, 'name'=>'Aceh Barat']);
        $this->insert('ref_city', ['id'=>1108, 'province_id'=>11, 'name'=>'Aceh Besar']);
        $this->insert('ref_city', ['id'=>1109, 'province_id'=>11, 'name'=>'Pidie']);
        $this->insert('ref_city', ['id'=>1110, 'province_id'=>11, 'name'=>'Bireuen']);
        $this->insert('ref_city', ['id'=>1111, 'province_id'=>11, 'name'=>'Aceh Utara']);
        $this->insert('ref_city', ['id'=>1112, 'province_id'=>11, 'name'=>'Aceh Barat Daya']);
        $this->insert('ref_city', ['id'=>1113, 'province_id'=>11, 'name'=>'Gayo Lues']);
        $this->insert('ref_city', ['id'=>1114, 'province_id'=>11, 'name'=>'Aceh Tamiang']);
        $this->insert('ref_city', ['id'=>1115, 'province_id'=>11, 'name'=>'Nagan Raya']);
        $this->insert('ref_city', ['id'=>1116, 'province_id'=>11, 'name'=>'Aceh Jaya']);
        $this->insert('ref_city', ['id'=>1117, 'province_id'=>11, 'name'=>'Bener Meriah']);
        $this->insert('ref_city', ['id'=>1118, 'province_id'=>11, 'name'=>'Pidie Jaya']);
        $this->insert('ref_city', ['id'=>1171, 'province_id'=>11, 'name'=>'Kota Banda Aceh']);
        $this->insert('ref_city', ['id'=>1172, 'province_id'=>11, 'name'=>'Kota Sabang']);
        $this->insert('ref_city', ['id'=>1173, 'province_id'=>11, 'name'=>'Kota Langsa']);
        $this->insert('ref_city', ['id'=>1174, 'province_id'=>11, 'name'=>'Kota Lhokseumawe']);
        $this->insert('ref_city', ['id'=>1175, 'province_id'=>11, 'name'=>'Kota Subulussalam']);
        $this->insert('ref_city', ['id'=>1201, 'province_id'=>12, 'name'=>'Nias']);
        $this->insert('ref_city', ['id'=>1202, 'province_id'=>12, 'name'=>'Mandailing Natal']);
        $this->insert('ref_city', ['id'=>1203, 'province_id'=>12, 'name'=>'Tapanuli Selatan']);
        $this->insert('ref_city', ['id'=>1204, 'province_id'=>12, 'name'=>'Tapanuli Tengah']);
        $this->insert('ref_city', ['id'=>1205, 'province_id'=>12, 'name'=>'Tapanuli Utara']);
        $this->insert('ref_city', ['id'=>1206, 'province_id'=>12, 'name'=>'Toba Samosir']);
        $this->insert('ref_city', ['id'=>1207, 'province_id'=>12, 'name'=>'Labuhan Batu']);
        $this->insert('ref_city', ['id'=>1208, 'province_id'=>12, 'name'=>'Asahan']);
        $this->insert('ref_city', ['id'=>1209, 'province_id'=>12, 'name'=>'Simalungun']);
        $this->insert('ref_city', ['id'=>1210, 'province_id'=>12, 'name'=>'Dairi']);
        $this->insert('ref_city', ['id'=>1211, 'province_id'=>12, 'name'=>'Karo']);
        $this->insert('ref_city', ['id'=>1212, 'province_id'=>12, 'name'=>'Deli Serdang']);
        $this->insert('ref_city', ['id'=>1213, 'province_id'=>12, 'name'=>'Langkat']);
        $this->insert('ref_city', ['id'=>1214, 'province_id'=>12, 'name'=>'Nias Selatan']);
        $this->insert('ref_city', ['id'=>1215, 'province_id'=>12, 'name'=>'Humbang Hasundutan']);
        $this->insert('ref_city', ['id'=>1216, 'province_id'=>12, 'name'=>'Pakpak Bharat']);
        $this->insert('ref_city', ['id'=>1217, 'province_id'=>12, 'name'=>'Samosir']);
        $this->insert('ref_city', ['id'=>1218, 'province_id'=>12, 'name'=>'Serdang Bedagai']);
        $this->insert('ref_city', ['id'=>1219, 'province_id'=>12, 'name'=>'Batu Bara']);
        $this->insert('ref_city', ['id'=>1220, 'province_id'=>12, 'name'=>'Padang Lawas Utara']);
        $this->insert('ref_city', ['id'=>1221, 'province_id'=>12, 'name'=>'Padang Lawas']);
        $this->insert('ref_city', ['id'=>1222, 'province_id'=>12, 'name'=>'Labuhan Batu Selatan']);
        $this->insert('ref_city', ['id'=>1223, 'province_id'=>12, 'name'=>'Labuhan Batu Utara']);
        $this->insert('ref_city', ['id'=>1224, 'province_id'=>12, 'name'=>'Nias Utara']);
        $this->insert('ref_city', ['id'=>1225, 'province_id'=>12, 'name'=>'Nias Barat']);
        $this->insert('ref_city', ['id'=>1271, 'province_id'=>12, 'name'=>'Kota Sibolga']);
        $this->insert('ref_city', ['id'=>1272, 'province_id'=>12, 'name'=>'Kota Tanjung Balai']);
        $this->insert('ref_city', ['id'=>1273, 'province_id'=>12, 'name'=>'Kota Pematang Siantar']);
        $this->insert('ref_city', ['id'=>1274, 'province_id'=>12, 'name'=>'Kota Tebing Tinggi']);
        $this->insert('ref_city', ['id'=>1275, 'province_id'=>12, 'name'=>'Kota Medan']);
        $this->insert('ref_city', ['id'=>1276, 'province_id'=>12, 'name'=>'Kota Binjai']);
        $this->insert('ref_city', ['id'=>1277, 'province_id'=>12, 'name'=>'Kota Padangsidimpuan']);
        $this->insert('ref_city', ['id'=>1278, 'province_id'=>12, 'name'=>'Kota Gunungsitoli']);
        $this->insert('ref_city', ['id'=>1301, 'province_id'=>13, 'name'=>'Kepulauan Mentawai']);
        $this->insert('ref_city', ['id'=>1302, 'province_id'=>13, 'name'=>'Pesisir Selatan']);
        $this->insert('ref_city', ['id'=>1303, 'province_id'=>13, 'name'=>'Solok']);
        $this->insert('ref_city', ['id'=>1304, 'province_id'=>13, 'name'=>'Sijunjung']);
        $this->insert('ref_city', ['id'=>1305, 'province_id'=>13, 'name'=>'Tanah Datar']);
        $this->insert('ref_city', ['id'=>1306, 'province_id'=>13, 'name'=>'Padang Pariaman']);
        $this->insert('ref_city', ['id'=>1307, 'province_id'=>13, 'name'=>'Agam']);
        $this->insert('ref_city', ['id'=>1308, 'province_id'=>13, 'name'=>'Lima Puluh Kota']);
        $this->insert('ref_city', ['id'=>1309, 'province_id'=>13, 'name'=>'Pasaman']);
        $this->insert('ref_city', ['id'=>1310, 'province_id'=>13, 'name'=>'Solok Selatan']);
        $this->insert('ref_city', ['id'=>1311, 'province_id'=>13, 'name'=>'Dharmasraya']);
        $this->insert('ref_city', ['id'=>1312, 'province_id'=>13, 'name'=>'Pasaman Barat']);
        $this->insert('ref_city', ['id'=>1371, 'province_id'=>13, 'name'=>'Kota Padang']);
        $this->insert('ref_city', ['id'=>1372, 'province_id'=>13, 'name'=>'Kota Solok']);
        $this->insert('ref_city', ['id'=>1373, 'province_id'=>13, 'name'=>'Kota Sawah Lunto']);
        $this->insert('ref_city', ['id'=>1374, 'province_id'=>13, 'name'=>'Kota Padang Panjang']);
        $this->insert('ref_city', ['id'=>1375, 'province_id'=>13, 'name'=>'Kota Bukittinggi']);
        $this->insert('ref_city', ['id'=>1376, 'province_id'=>13, 'name'=>'Kota Payakumbuh']);
        $this->insert('ref_city', ['id'=>1377, 'province_id'=>13, 'name'=>'Kota Pariaman']);
        $this->insert('ref_city', ['id'=>1401, 'province_id'=>14, 'name'=>'Kuantan Singingi']);
        $this->insert('ref_city', ['id'=>1402, 'province_id'=>14, 'name'=>'Indragiri Hulu']);
        $this->insert('ref_city', ['id'=>1403, 'province_id'=>14, 'name'=>'Indragiri Hilir']);
        $this->insert('ref_city', ['id'=>1404, 'province_id'=>14, 'name'=>'Pelalawan']);
        $this->insert('ref_city', ['id'=>1405, 'province_id'=>14, 'name'=>'S I A K']);
        $this->insert('ref_city', ['id'=>1406, 'province_id'=>14, 'name'=>'Kampar']);
        $this->insert('ref_city', ['id'=>1407, 'province_id'=>14, 'name'=>'Rokan Hulu']);
        $this->insert('ref_city', ['id'=>1408, 'province_id'=>14, 'name'=>'Bengkalis']);
        $this->insert('ref_city', ['id'=>1409, 'province_id'=>14, 'name'=>'Rokan Hilir']);
        $this->insert('ref_city', ['id'=>1410, 'province_id'=>14, 'name'=>'Kepulauan Meranti']);
        $this->insert('ref_city', ['id'=>1471, 'province_id'=>14, 'name'=>'Kota Pekanbaru']);
        $this->insert('ref_city', ['id'=>1473, 'province_id'=>14, 'name'=>'Kota D U M A I']);
        $this->insert('ref_city', ['id'=>1501, 'province_id'=>15, 'name'=>'Kerinci']);
        $this->insert('ref_city', ['id'=>1502, 'province_id'=>15, 'name'=>'Merangin']);
        $this->insert('ref_city', ['id'=>1503, 'province_id'=>15, 'name'=>'Sarolangun']);
        $this->insert('ref_city', ['id'=>1504, 'province_id'=>15, 'name'=>'Batang Hari']);
        $this->insert('ref_city', ['id'=>1505, 'province_id'=>15, 'name'=>'Muaro Jambi']);
        $this->insert('ref_city', ['id'=>1506, 'province_id'=>15, 'name'=>'Tanjung Jabung Timur']);
        $this->insert('ref_city', ['id'=>1507, 'province_id'=>15, 'name'=>'Tanjung Jabung Barat']);
        $this->insert('ref_city', ['id'=>1508, 'province_id'=>15, 'name'=>'Tebo']);
        $this->insert('ref_city', ['id'=>1509, 'province_id'=>15, 'name'=>'Bungo']);
        $this->insert('ref_city', ['id'=>1571, 'province_id'=>15, 'name'=>'Kota Jambi']);
        $this->insert('ref_city', ['id'=>1572, 'province_id'=>15, 'name'=>'Kota Sungai Penuh']);
        $this->insert('ref_city', ['id'=>1601, 'province_id'=>16, 'name'=>'Ogan Komering Ulu']);
        $this->insert('ref_city', ['id'=>1602, 'province_id'=>16, 'name'=>'Ogan Komering Ilir']);
        $this->insert('ref_city', ['id'=>1603, 'province_id'=>16, 'name'=>'Muara Enim']);
        $this->insert('ref_city', ['id'=>1604, 'province_id'=>16, 'name'=>'Lahat']);
        $this->insert('ref_city', ['id'=>1605, 'province_id'=>16, 'name'=>'Musi Rawas']);
        $this->insert('ref_city', ['id'=>1606, 'province_id'=>16, 'name'=>'Musi Banyuasin']);
        $this->insert('ref_city', ['id'=>1607, 'province_id'=>16, 'name'=>'Banyu Asin']);
        $this->insert('ref_city', ['id'=>1608, 'province_id'=>16, 'name'=>'Ogan Komering Ulu Selatan']);
        $this->insert('ref_city', ['id'=>1609, 'province_id'=>16, 'name'=>'Ogan Komering Ulu Timur']);
        $this->insert('ref_city', ['id'=>1610, 'province_id'=>16, 'name'=>'Ogan Ilir']);
        $this->insert('ref_city', ['id'=>1611, 'province_id'=>16, 'name'=>'Empat Lawang']);
        $this->insert('ref_city', ['id'=>1671, 'province_id'=>16, 'name'=>'Kota Palembang']);
        $this->insert('ref_city', ['id'=>1672, 'province_id'=>16, 'name'=>'Kota Prabumulih']);
        $this->insert('ref_city', ['id'=>1673, 'province_id'=>16, 'name'=>'Kota Pagar Alam']);
        $this->insert('ref_city', ['id'=>1674, 'province_id'=>16, 'name'=>'Kota Lubuklinggau']);
        $this->insert('ref_city', ['id'=>1701, 'province_id'=>17, 'name'=>'Bengkulu Selatan']);
        $this->insert('ref_city', ['id'=>1702, 'province_id'=>17, 'name'=>'Rejang Lebong']);
        $this->insert('ref_city', ['id'=>1703, 'province_id'=>17, 'name'=>'Bengkulu Utara']);
        $this->insert('ref_city', ['id'=>1704, 'province_id'=>17, 'name'=>'Kaur']);
        $this->insert('ref_city', ['id'=>1705, 'province_id'=>17, 'name'=>'Seluma']);
        $this->insert('ref_city', ['id'=>1706, 'province_id'=>17, 'name'=>'Mukomuko']);
        $this->insert('ref_city', ['id'=>1707, 'province_id'=>17, 'name'=>'Lebong']);
        $this->insert('ref_city', ['id'=>1708, 'province_id'=>17, 'name'=>'Kepahiang']);
        $this->insert('ref_city', ['id'=>1709, 'province_id'=>17, 'name'=>'Bengkulu Tengah']);
        $this->insert('ref_city', ['id'=>1771, 'province_id'=>17, 'name'=>'Kota Bengkulu']);
        $this->insert('ref_city', ['id'=>1801, 'province_id'=>18, 'name'=>'Lampung Barat']);
        $this->insert('ref_city', ['id'=>1802, 'province_id'=>18, 'name'=>'Tanggamus']);
        $this->insert('ref_city', ['id'=>1803, 'province_id'=>18, 'name'=>'Lampung Selatan']);
        $this->insert('ref_city', ['id'=>1804, 'province_id'=>18, 'name'=>'Lampung Timur']);
        $this->insert('ref_city', ['id'=>1805, 'province_id'=>18, 'name'=>'Lampung Tengah']);
        $this->insert('ref_city', ['id'=>1806, 'province_id'=>18, 'name'=>'Lampung Utara']);
        $this->insert('ref_city', ['id'=>1807, 'province_id'=>18, 'name'=>'Way Kanan']);
        $this->insert('ref_city', ['id'=>1808, 'province_id'=>18, 'name'=>'Tulangbawang']);
        $this->insert('ref_city', ['id'=>1809, 'province_id'=>18, 'name'=>'Pesawaran']);
        $this->insert('ref_city', ['id'=>1810, 'province_id'=>18, 'name'=>'Pringsewu']);
        $this->insert('ref_city', ['id'=>1811, 'province_id'=>18, 'name'=>'Mesuji']);
        $this->insert('ref_city', ['id'=>1812, 'province_id'=>18, 'name'=>'Tulang Bawang Barat']);
        $this->insert('ref_city', ['id'=>1813, 'province_id'=>18, 'name'=>'Pesisir Barat']);
        $this->insert('ref_city', ['id'=>1871, 'province_id'=>18, 'name'=>'Kota Bandar Lampung']);
        $this->insert('ref_city', ['id'=>1872, 'province_id'=>18, 'name'=>'Kota Metro']);
        $this->insert('ref_city', ['id'=>1901, 'province_id'=>19, 'name'=>'Bangka']);
        $this->insert('ref_city', ['id'=>1902, 'province_id'=>19, 'name'=>'Belitung']);
        $this->insert('ref_city', ['id'=>1903, 'province_id'=>19, 'name'=>'Bangka Barat']);
        $this->insert('ref_city', ['id'=>1904, 'province_id'=>19, 'name'=>'Bangka Tengah']);
        $this->insert('ref_city', ['id'=>1905, 'province_id'=>19, 'name'=>'Bangka Selatan']);
        $this->insert('ref_city', ['id'=>1906, 'province_id'=>19, 'name'=>'Belitung Timur']);
        $this->insert('ref_city', ['id'=>1971, 'province_id'=>19, 'name'=>'Kota Pangkal Pinang']);
        $this->insert('ref_city', ['id'=>2101, 'province_id'=>21, 'name'=>'Karimun']);
        $this->insert('ref_city', ['id'=>2102, 'province_id'=>21, 'name'=>'Bintan']);
        $this->insert('ref_city', ['id'=>2103, 'province_id'=>21, 'name'=>'Natuna']);
        $this->insert('ref_city', ['id'=>2104, 'province_id'=>21, 'name'=>'Lingga']);
        $this->insert('ref_city', ['id'=>2105, 'province_id'=>21, 'name'=>'Kepulauan Anambas']);
        $this->insert('ref_city', ['id'=>2171, 'province_id'=>21, 'name'=>'Kota B A T A M']);
        $this->insert('ref_city', ['id'=>2172, 'province_id'=>21, 'name'=>'Kota Tanjung Pinang']);
        $this->insert('ref_city', ['id'=>3101, 'province_id'=>31, 'name'=>'Kepulauan Seribu']);
        $this->insert('ref_city', ['id'=>3171, 'province_id'=>31, 'name'=>'Kota Jakarta Selatan']);
        $this->insert('ref_city', ['id'=>3172, 'province_id'=>31, 'name'=>'Kota Jakarta Timur']);
        $this->insert('ref_city', ['id'=>3173, 'province_id'=>31, 'name'=>'Kota Jakarta Pusat']);
        $this->insert('ref_city', ['id'=>3174, 'province_id'=>31, 'name'=>'Kota Jakarta Barat']);
        $this->insert('ref_city', ['id'=>3175, 'province_id'=>31, 'name'=>'Kota Jakarta Utara']);
        $this->insert('ref_city', ['id'=>3201, 'province_id'=>32, 'name'=>'Bogor']);
        $this->insert('ref_city', ['id'=>3202, 'province_id'=>32, 'name'=>'Sukabumi']);
        $this->insert('ref_city', ['id'=>3203, 'province_id'=>32, 'name'=>'Cianjur']);
        $this->insert('ref_city', ['id'=>3204, 'province_id'=>32, 'name'=>'Bandung']);
        $this->insert('ref_city', ['id'=>3205, 'province_id'=>32, 'name'=>'Garut']);
        $this->insert('ref_city', ['id'=>3206, 'province_id'=>32, 'name'=>'Tasikmalaya']);
        $this->insert('ref_city', ['id'=>3207, 'province_id'=>32, 'name'=>'Ciamis']);
        $this->insert('ref_city', ['id'=>3208, 'province_id'=>32, 'name'=>'Kuningan']);
        $this->insert('ref_city', ['id'=>3209, 'province_id'=>32, 'name'=>'Cirebon']);
        $this->insert('ref_city', ['id'=>3210, 'province_id'=>32, 'name'=>'Majalengka']);
        $this->insert('ref_city', ['id'=>3211, 'province_id'=>32, 'name'=>'Sumedang']);
        $this->insert('ref_city', ['id'=>3212, 'province_id'=>32, 'name'=>'Indramayu']);
        $this->insert('ref_city', ['id'=>3213, 'province_id'=>32, 'name'=>'Subang']);
        $this->insert('ref_city', ['id'=>3214, 'province_id'=>32, 'name'=>'Purwakarta']);
        $this->insert('ref_city', ['id'=>3215, 'province_id'=>32, 'name'=>'Karawang']);
        $this->insert('ref_city', ['id'=>3216, 'province_id'=>32, 'name'=>'Bekasi']);
        $this->insert('ref_city', ['id'=>3217, 'province_id'=>32, 'name'=>'Bandung Barat']);
        $this->insert('ref_city', ['id'=>3218, 'province_id'=>32, 'name'=>'Pangandaran']);
        $this->insert('ref_city', ['id'=>3271, 'province_id'=>32, 'name'=>'Kota Bogor']);
        $this->insert('ref_city', ['id'=>3272, 'province_id'=>32, 'name'=>'Kota Sukabumi']);
        $this->insert('ref_city', ['id'=>3273, 'province_id'=>32, 'name'=>'Kota Bandung']);
        $this->insert('ref_city', ['id'=>3274, 'province_id'=>32, 'name'=>'Kota Cirebon']);
        $this->insert('ref_city', ['id'=>3275, 'province_id'=>32, 'name'=>'Kota Bekasi']);
        $this->insert('ref_city', ['id'=>3276, 'province_id'=>32, 'name'=>'Kota Depok']);
        $this->insert('ref_city', ['id'=>3277, 'province_id'=>32, 'name'=>'Kota Cimahi']);
        $this->insert('ref_city', ['id'=>3278, 'province_id'=>32, 'name'=>'Kota Tasikmalaya']);
        $this->insert('ref_city', ['id'=>3279, 'province_id'=>32, 'name'=>'Kota Banjar']);
        $this->insert('ref_city', ['id'=>3301, 'province_id'=>33, 'name'=>'Cilacap']);
        $this->insert('ref_city', ['id'=>3302, 'province_id'=>33, 'name'=>'Banyumas']);
        $this->insert('ref_city', ['id'=>3303, 'province_id'=>33, 'name'=>'Purbalingga']);
        $this->insert('ref_city', ['id'=>3304, 'province_id'=>33, 'name'=>'Banjarnegara']);
        $this->insert('ref_city', ['id'=>3305, 'province_id'=>33, 'name'=>'Kebumen']);
        $this->insert('ref_city', ['id'=>3306, 'province_id'=>33, 'name'=>'Purworejo']);
        $this->insert('ref_city', ['id'=>3307, 'province_id'=>33, 'name'=>'Wonosobo']);
        $this->insert('ref_city', ['id'=>3308, 'province_id'=>33, 'name'=>'Magelang']);
        $this->insert('ref_city', ['id'=>3309, 'province_id'=>33, 'name'=>'Boyolali']);
        $this->insert('ref_city', ['id'=>3310, 'province_id'=>33, 'name'=>'Klaten']);
        $this->insert('ref_city', ['id'=>3311, 'province_id'=>33, 'name'=>'Sukoharjo']);
        $this->insert('ref_city', ['id'=>3312, 'province_id'=>33, 'name'=>'Wonogiri']);
        $this->insert('ref_city', ['id'=>3313, 'province_id'=>33, 'name'=>'Karanganyar']);
        $this->insert('ref_city', ['id'=>3314, 'province_id'=>33, 'name'=>'Sragen']);
        $this->insert('ref_city', ['id'=>3315, 'province_id'=>33, 'name'=>'Grobogan']);
        $this->insert('ref_city', ['id'=>3316, 'province_id'=>33, 'name'=>'Blora']);
        $this->insert('ref_city', ['id'=>3317, 'province_id'=>33, 'name'=>'Rembang']);
        $this->insert('ref_city', ['id'=>3318, 'province_id'=>33, 'name'=>'Pati']);
        $this->insert('ref_city', ['id'=>3319, 'province_id'=>33, 'name'=>'Kudus']);
        $this->insert('ref_city', ['id'=>3320, 'province_id'=>33, 'name'=>'Jepara']);
        $this->insert('ref_city', ['id'=>3321, 'province_id'=>33, 'name'=>'Demak']);
        $this->insert('ref_city', ['id'=>3322, 'province_id'=>33, 'name'=>'Semarang']);
        $this->insert('ref_city', ['id'=>3323, 'province_id'=>33, 'name'=>'Temanggung']);
        $this->insert('ref_city', ['id'=>3324, 'province_id'=>33, 'name'=>'Kendal']);
        $this->insert('ref_city', ['id'=>3325, 'province_id'=>33, 'name'=>'Batang']);
        $this->insert('ref_city', ['id'=>3326, 'province_id'=>33, 'name'=>'Pekalongan']);
        $this->insert('ref_city', ['id'=>3327, 'province_id'=>33, 'name'=>'Pemalang']);
        $this->insert('ref_city', ['id'=>3328, 'province_id'=>33, 'name'=>'Tegal']);
        $this->insert('ref_city', ['id'=>3329, 'province_id'=>33, 'name'=>'Brebes']);
        $this->insert('ref_city', ['id'=>3371, 'province_id'=>33, 'name'=>'Kota Magelang']);
        $this->insert('ref_city', ['id'=>3372, 'province_id'=>33, 'name'=>'Kota Surakarta']);
        $this->insert('ref_city', ['id'=>3373, 'province_id'=>33, 'name'=>'Kota Salatiga']);
        $this->insert('ref_city', ['id'=>3374, 'province_id'=>33, 'name'=>'Kota Semarang']);
        $this->insert('ref_city', ['id'=>3375, 'province_id'=>33, 'name'=>'Kota Pekalongan']);
        $this->insert('ref_city', ['id'=>3376, 'province_id'=>33, 'name'=>'Kota Tegal']);
        $this->insert('ref_city', ['id'=>3401, 'province_id'=>34, 'name'=>'Kulon Progo']);
        $this->insert('ref_city', ['id'=>3402, 'province_id'=>34, 'name'=>'Bantul']);
        $this->insert('ref_city', ['id'=>3403, 'province_id'=>34, 'name'=>'Gunung Kidul']);
        $this->insert('ref_city', ['id'=>3404, 'province_id'=>34, 'name'=>'Sleman']);
        $this->insert('ref_city', ['id'=>3471, 'province_id'=>34, 'name'=>'Kota Yogyakarta']);
        $this->insert('ref_city', ['id'=>3501, 'province_id'=>35, 'name'=>'Pacitan']);
        $this->insert('ref_city', ['id'=>3502, 'province_id'=>35, 'name'=>'Ponorogo']);
        $this->insert('ref_city', ['id'=>3503, 'province_id'=>35, 'name'=>'Trenggalek']);
        $this->insert('ref_city', ['id'=>3504, 'province_id'=>35, 'name'=>'Tulungagung']);
        $this->insert('ref_city', ['id'=>3505, 'province_id'=>35, 'name'=>'Blitar']);
        $this->insert('ref_city', ['id'=>3506, 'province_id'=>35, 'name'=>'Kediri']);
        $this->insert('ref_city', ['id'=>3507, 'province_id'=>35, 'name'=>'Malang']);
        $this->insert('ref_city', ['id'=>3508, 'province_id'=>35, 'name'=>'Lumajang']);
        $this->insert('ref_city', ['id'=>3509, 'province_id'=>35, 'name'=>'Jember']);
        $this->insert('ref_city', ['id'=>3510, 'province_id'=>35, 'name'=>'Banyuwangi']);
        $this->insert('ref_city', ['id'=>3511, 'province_id'=>35, 'name'=>'Bondowoso']);
        $this->insert('ref_city', ['id'=>3512, 'province_id'=>35, 'name'=>'Situbondo']);
        $this->insert('ref_city', ['id'=>3513, 'province_id'=>35, 'name'=>'Probolinggo']);
        $this->insert('ref_city', ['id'=>3514, 'province_id'=>35, 'name'=>'Pasuruan']);
        $this->insert('ref_city', ['id'=>3515, 'province_id'=>35, 'name'=>'Sidoarjo']);
        $this->insert('ref_city', ['id'=>3516, 'province_id'=>35, 'name'=>'Mojokerto']);
        $this->insert('ref_city', ['id'=>3517, 'province_id'=>35, 'name'=>'Jombang']);
        $this->insert('ref_city', ['id'=>3518, 'province_id'=>35, 'name'=>'Nganjuk']);
        $this->insert('ref_city', ['id'=>3519, 'province_id'=>35, 'name'=>'Madiun']);
        $this->insert('ref_city', ['id'=>3520, 'province_id'=>35, 'name'=>'Magetan']);
        $this->insert('ref_city', ['id'=>3521, 'province_id'=>35, 'name'=>'Ngawi']);
        $this->insert('ref_city', ['id'=>3522, 'province_id'=>35, 'name'=>'Bojonegoro']);
        $this->insert('ref_city', ['id'=>3523, 'province_id'=>35, 'name'=>'Tuban']);
        $this->insert('ref_city', ['id'=>3524, 'province_id'=>35, 'name'=>'Lamongan']);
        $this->insert('ref_city', ['id'=>3525, 'province_id'=>35, 'name'=>'Gresik']);
        $this->insert('ref_city', ['id'=>3526, 'province_id'=>35, 'name'=>'Bangkalan']);
        $this->insert('ref_city', ['id'=>3527, 'province_id'=>35, 'name'=>'Sampang']);
        $this->insert('ref_city', ['id'=>3528, 'province_id'=>35, 'name'=>'Pamekasan']);
        $this->insert('ref_city', ['id'=>3529, 'province_id'=>35, 'name'=>'Sumenep']);
        $this->insert('ref_city', ['id'=>3571, 'province_id'=>35, 'name'=>'Kota Kediri']);
        $this->insert('ref_city', ['id'=>3572, 'province_id'=>35, 'name'=>'Kota Blitar']);
        $this->insert('ref_city', ['id'=>3573, 'province_id'=>35, 'name'=>'Kota Malang']);
        $this->insert('ref_city', ['id'=>3574, 'province_id'=>35, 'name'=>'Kota Probolinggo']);
        $this->insert('ref_city', ['id'=>3575, 'province_id'=>35, 'name'=>'Kota Pasuruan']);
        $this->insert('ref_city', ['id'=>3576, 'province_id'=>35, 'name'=>'Kota Mojokerto']);
        $this->insert('ref_city', ['id'=>3577, 'province_id'=>35, 'name'=>'Kota Madiun']);
        $this->insert('ref_city', ['id'=>3578, 'province_id'=>35, 'name'=>'Kota Surabaya']);
        $this->insert('ref_city', ['id'=>3579, 'province_id'=>35, 'name'=>'Kota Batu']);
        $this->insert('ref_city', ['id'=>3601, 'province_id'=>36, 'name'=>'Pandeglang']);
        $this->insert('ref_city', ['id'=>3602, 'province_id'=>36, 'name'=>'Lebak']);
        $this->insert('ref_city', ['id'=>3603, 'province_id'=>36, 'name'=>'Tangerang']);
        $this->insert('ref_city', ['id'=>3604, 'province_id'=>36, 'name'=>'Serang']);
        $this->insert('ref_city', ['id'=>3671, 'province_id'=>36, 'name'=>'Kota Tangerang']);
        $this->insert('ref_city', ['id'=>3672, 'province_id'=>36, 'name'=>'Kota Cilegon']);
        $this->insert('ref_city', ['id'=>3673, 'province_id'=>36, 'name'=>'Kota Serang']);
        $this->insert('ref_city', ['id'=>3674, 'province_id'=>36, 'name'=>'Kota Tangerang Selatan']);
        $this->insert('ref_city', ['id'=>5101, 'province_id'=>51, 'name'=>'Jembrana']);
        $this->insert('ref_city', ['id'=>5102, 'province_id'=>51, 'name'=>'Tabanan']);
        $this->insert('ref_city', ['id'=>5103, 'province_id'=>51, 'name'=>'Badung']);
        $this->insert('ref_city', ['id'=>5104, 'province_id'=>51, 'name'=>'Gianyar']);
        $this->insert('ref_city', ['id'=>5105, 'province_id'=>51, 'name'=>'Klungkung']);
        $this->insert('ref_city', ['id'=>5106, 'province_id'=>51, 'name'=>'Bangli']);
        $this->insert('ref_city', ['id'=>5107, 'province_id'=>51, 'name'=>'Karang Asem']);
        $this->insert('ref_city', ['id'=>5108, 'province_id'=>51, 'name'=>'Buleleng']);
        $this->insert('ref_city', ['id'=>5171, 'province_id'=>51, 'name'=>'Kota Denpasar']);
        $this->insert('ref_city', ['id'=>5201, 'province_id'=>52, 'name'=>'Lombok Barat']);
        $this->insert('ref_city', ['id'=>5202, 'province_id'=>52, 'name'=>'Lombok Tengah']);
        $this->insert('ref_city', ['id'=>5203, 'province_id'=>52, 'name'=>'Lombok Timur']);
        $this->insert('ref_city', ['id'=>5204, 'province_id'=>52, 'name'=>'Sumbawa']);
        $this->insert('ref_city', ['id'=>5205, 'province_id'=>52, 'name'=>'Dompu']);
        $this->insert('ref_city', ['id'=>5206, 'province_id'=>52, 'name'=>'Bima']);
        $this->insert('ref_city', ['id'=>5207, 'province_id'=>52, 'name'=>'Sumbawa Barat']);
        $this->insert('ref_city', ['id'=>5208, 'province_id'=>52, 'name'=>'Lombok Utara']);
        $this->insert('ref_city', ['id'=>5271, 'province_id'=>52, 'name'=>'Kota Mataram']);
        $this->insert('ref_city', ['id'=>5272, 'province_id'=>52, 'name'=>'Kota Bima']);
        $this->insert('ref_city', ['id'=>5301, 'province_id'=>53, 'name'=>'Sumba Barat']);
        $this->insert('ref_city', ['id'=>5302, 'province_id'=>53, 'name'=>'Sumba Timur']);
        $this->insert('ref_city', ['id'=>5303, 'province_id'=>53, 'name'=>'Kupang']);
        $this->insert('ref_city', ['id'=>5304, 'province_id'=>53, 'name'=>'Timor Tengah Selatan']);
        $this->insert('ref_city', ['id'=>5305, 'province_id'=>53, 'name'=>'Timor Tengah Utara']);
        $this->insert('ref_city', ['id'=>5306, 'province_id'=>53, 'name'=>'Belu']);
        $this->insert('ref_city', ['id'=>5307, 'province_id'=>53, 'name'=>'Alor']);
        $this->insert('ref_city', ['id'=>5308, 'province_id'=>53, 'name'=>'Lembata']);
        $this->insert('ref_city', ['id'=>5309, 'province_id'=>53, 'name'=>'Flores Timur']);
        $this->insert('ref_city', ['id'=>5310, 'province_id'=>53, 'name'=>'Sikka']);
        $this->insert('ref_city', ['id'=>5311, 'province_id'=>53, 'name'=>'Ende']);
        $this->insert('ref_city', ['id'=>5312, 'province_id'=>53, 'name'=>'Ngada']);
        $this->insert('ref_city', ['id'=>5313, 'province_id'=>53, 'name'=>'Manggarai']);
        $this->insert('ref_city', ['id'=>5314, 'province_id'=>53, 'name'=>'Rote Ndao']);
        $this->insert('ref_city', ['id'=>5315, 'province_id'=>53, 'name'=>'Manggarai Barat']);
        $this->insert('ref_city', ['id'=>5316, 'province_id'=>53, 'name'=>'Sumba Tengah']);
        $this->insert('ref_city', ['id'=>5317, 'province_id'=>53, 'name'=>'Sumba Barat Daya']);
        $this->insert('ref_city', ['id'=>5318, 'province_id'=>53, 'name'=>'Nagekeo']);
        $this->insert('ref_city', ['id'=>5319, 'province_id'=>53, 'name'=>'Manggarai Timur']);
        $this->insert('ref_city', ['id'=>5320, 'province_id'=>53, 'name'=>'Sabu Raijua']);
        $this->insert('ref_city', ['id'=>5371, 'province_id'=>53, 'name'=>'Kota Kupang']);
        $this->insert('ref_city', ['id'=>6101, 'province_id'=>61, 'name'=>'Sambas']);
        $this->insert('ref_city', ['id'=>6102, 'province_id'=>61, 'name'=>'Bengkayang']);
        $this->insert('ref_city', ['id'=>6103, 'province_id'=>61, 'name'=>'Landak']);
        $this->insert('ref_city', ['id'=>6104, 'province_id'=>61, 'name'=>'Pontianak']);
        $this->insert('ref_city', ['id'=>6105, 'province_id'=>61, 'name'=>'Sanggau']);
        $this->insert('ref_city', ['id'=>6106, 'province_id'=>61, 'name'=>'Ketapang']);
        $this->insert('ref_city', ['id'=>6107, 'province_id'=>61, 'name'=>'Sintang']);
        $this->insert('ref_city', ['id'=>6108, 'province_id'=>61, 'name'=>'Kapuas Hulu']);
        $this->insert('ref_city', ['id'=>6109, 'province_id'=>61, 'name'=>'Sekadau']);
        $this->insert('ref_city', ['id'=>6110, 'province_id'=>61, 'name'=>'Melawi']);
        $this->insert('ref_city', ['id'=>6111, 'province_id'=>61, 'name'=>'Kayong Utara']);
        $this->insert('ref_city', ['id'=>6112, 'province_id'=>61, 'name'=>'Kubu Raya']);
        $this->insert('ref_city', ['id'=>6171, 'province_id'=>61, 'name'=>'Kota Pontianak']);
        $this->insert('ref_city', ['id'=>6172, 'province_id'=>61, 'name'=>'Kota Singkawang']);
        $this->insert('ref_city', ['id'=>6201, 'province_id'=>62, 'name'=>'Kotawaringin Barat']);
        $this->insert('ref_city', ['id'=>6202, 'province_id'=>62, 'name'=>'Kotawaringin Timur']);
        $this->insert('ref_city', ['id'=>6203, 'province_id'=>62, 'name'=>'Kapuas']);
        $this->insert('ref_city', ['id'=>6204, 'province_id'=>62, 'name'=>'Barito Selatan']);
        $this->insert('ref_city', ['id'=>6205, 'province_id'=>62, 'name'=>'Barito Utara']);
        $this->insert('ref_city', ['id'=>6206, 'province_id'=>62, 'name'=>'Sukamara']);
        $this->insert('ref_city', ['id'=>6207, 'province_id'=>62, 'name'=>'Lamandau']);
        $this->insert('ref_city', ['id'=>6208, 'province_id'=>62, 'name'=>'Seruyan']);
        $this->insert('ref_city', ['id'=>6209, 'province_id'=>62, 'name'=>'Katingan']);
        $this->insert('ref_city', ['id'=>6210, 'province_id'=>62, 'name'=>'Pulang Pisau']);
        $this->insert('ref_city', ['id'=>6211, 'province_id'=>62, 'name'=>'Gunung Mas']);
        $this->insert('ref_city', ['id'=>6212, 'province_id'=>62, 'name'=>'Barito Timur']);
        $this->insert('ref_city', ['id'=>6213, 'province_id'=>62, 'name'=>'Murung Raya']);
        $this->insert('ref_city', ['id'=>6271, 'province_id'=>62, 'name'=>'Kota Palangka Raya']);
        $this->insert('ref_city', ['id'=>6301, 'province_id'=>63, 'name'=>'Tanah Laut']);
        $this->insert('ref_city', ['id'=>6302, 'province_id'=>63, 'name'=>'Kota Baru']);
        $this->insert('ref_city', ['id'=>6303, 'province_id'=>63, 'name'=>'Banjar']);
        $this->insert('ref_city', ['id'=>6304, 'province_id'=>63, 'name'=>'Barito Kuala']);
        $this->insert('ref_city', ['id'=>6305, 'province_id'=>63, 'name'=>'Tapin']);
        $this->insert('ref_city', ['id'=>6306, 'province_id'=>63, 'name'=>'Hulu Sungai Selatan']);
        $this->insert('ref_city', ['id'=>6307, 'province_id'=>63, 'name'=>'Hulu Sungai Tengah']);
        $this->insert('ref_city', ['id'=>6308, 'province_id'=>63, 'name'=>'Hulu Sungai Utara']);
        $this->insert('ref_city', ['id'=>6309, 'province_id'=>63, 'name'=>'Tabalong']);
        $this->insert('ref_city', ['id'=>6310, 'province_id'=>63, 'name'=>'Tanah Bumbu']);
        $this->insert('ref_city', ['id'=>6311, 'province_id'=>63, 'name'=>'Balangan']);
        $this->insert('ref_city', ['id'=>6371, 'province_id'=>63, 'name'=>'Kota Banjarmasin']);
        $this->insert('ref_city', ['id'=>6372, 'province_id'=>63, 'name'=>'Kota Banjar Baru']);
        $this->insert('ref_city', ['id'=>6401, 'province_id'=>64, 'name'=>'Paser']);
        $this->insert('ref_city', ['id'=>6402, 'province_id'=>64, 'name'=>'Kutai Barat']);
        $this->insert('ref_city', ['id'=>6403, 'province_id'=>64, 'name'=>'Kutai Kartanegara']);
        $this->insert('ref_city', ['id'=>6404, 'province_id'=>64, 'name'=>'Kutai Timur']);
        $this->insert('ref_city', ['id'=>6405, 'province_id'=>64, 'name'=>'Berau']);
        $this->insert('ref_city', ['id'=>6409, 'province_id'=>64, 'name'=>'Penajam Paser Utara']);
        $this->insert('ref_city', ['id'=>6471, 'province_id'=>64, 'name'=>'Kota Balikpapan']);
        $this->insert('ref_city', ['id'=>6472, 'province_id'=>64, 'name'=>'Kota Samarinda']);
        $this->insert('ref_city', ['id'=>6474, 'province_id'=>64, 'name'=>'Kota Bontang']);
        $this->insert('ref_city', ['id'=>6501, 'province_id'=>65, 'name'=>'Malinau']);
        $this->insert('ref_city', ['id'=>6502, 'province_id'=>65, 'name'=>'Bulungan']);
        $this->insert('ref_city', ['id'=>6503, 'province_id'=>65, 'name'=>'Tana Tidung']);
        $this->insert('ref_city', ['id'=>6504, 'province_id'=>65, 'name'=>'Nunukan']);
        $this->insert('ref_city', ['id'=>6571, 'province_id'=>65, 'name'=>'Kota Tarakan']);
        $this->insert('ref_city', ['id'=>7101, 'province_id'=>71, 'name'=>'Bolaang Mongondow']);
        $this->insert('ref_city', ['id'=>7102, 'province_id'=>71, 'name'=>'Minahasa']);
        $this->insert('ref_city', ['id'=>7103, 'province_id'=>71, 'name'=>'Kepulauan Sangihe']);
        $this->insert('ref_city', ['id'=>7104, 'province_id'=>71, 'name'=>'Kepulauan Talaud']);
        $this->insert('ref_city', ['id'=>7105, 'province_id'=>71, 'name'=>'Minahasa Selatan']);
        $this->insert('ref_city', ['id'=>7106, 'province_id'=>71, 'name'=>'Minahasa Utara']);
        $this->insert('ref_city', ['id'=>7107, 'province_id'=>71, 'name'=>'Bolaang Mongondow Utara']);
        $this->insert('ref_city', ['id'=>7108, 'province_id'=>71, 'name'=>'Siau Tagulandang Biaro']);
        $this->insert('ref_city', ['id'=>7109, 'province_id'=>71, 'name'=>'Minahasa Tenggara']);
        $this->insert('ref_city', ['id'=>7110, 'province_id'=>71, 'name'=>'Bolaang Mongondow Selatan']);
        $this->insert('ref_city', ['id'=>7111, 'province_id'=>71, 'name'=>'Bolaang Mongondow Timur']);
        $this->insert('ref_city', ['id'=>7171, 'province_id'=>71, 'name'=>'Kota Manado']);
        $this->insert('ref_city', ['id'=>7172, 'province_id'=>71, 'name'=>'Kota Bitung']);
        $this->insert('ref_city', ['id'=>7173, 'province_id'=>71, 'name'=>'Kota Tomohon']);
        $this->insert('ref_city', ['id'=>7174, 'province_id'=>71, 'name'=>'Kota Kotamobagu']);
        $this->insert('ref_city', ['id'=>7201, 'province_id'=>72, 'name'=>'Banggai Kepulauan']);
        $this->insert('ref_city', ['id'=>7202, 'province_id'=>72, 'name'=>'Banggai']);
        $this->insert('ref_city', ['id'=>7203, 'province_id'=>72, 'name'=>'Morowali']);
        $this->insert('ref_city', ['id'=>7204, 'province_id'=>72, 'name'=>'Poso']);
        $this->insert('ref_city', ['id'=>7205, 'province_id'=>72, 'name'=>'Donggala']);
        $this->insert('ref_city', ['id'=>7206, 'province_id'=>72, 'name'=>'Toli-toli']);
        $this->insert('ref_city', ['id'=>7207, 'province_id'=>72, 'name'=>'Buol']);
        $this->insert('ref_city', ['id'=>7208, 'province_id'=>72, 'name'=>'Parigi Moutong']);
        $this->insert('ref_city', ['id'=>7209, 'province_id'=>72, 'name'=>'Tojo Una-una']);
        $this->insert('ref_city', ['id'=>7210, 'province_id'=>72, 'name'=>'Sigi']);
        $this->insert('ref_city', ['id'=>7271, 'province_id'=>72, 'name'=>'Kota Palu']);
        $this->insert('ref_city', ['id'=>7301, 'province_id'=>73, 'name'=>'Kepulauan Selayar']);
        $this->insert('ref_city', ['id'=>7302, 'province_id'=>73, 'name'=>'Bulukumba']);
        $this->insert('ref_city', ['id'=>7303, 'province_id'=>73, 'name'=>'Bantaeng']);
        $this->insert('ref_city', ['id'=>7304, 'province_id'=>73, 'name'=>'Jeneponto']);
        $this->insert('ref_city', ['id'=>7305, 'province_id'=>73, 'name'=>'Takalar']);
        $this->insert('ref_city', ['id'=>7306, 'province_id'=>73, 'name'=>'Gowa']);
        $this->insert('ref_city', ['id'=>7307, 'province_id'=>73, 'name'=>'Sinjai']);
        $this->insert('ref_city', ['id'=>7308, 'province_id'=>73, 'name'=>'Maros']);
        $this->insert('ref_city', ['id'=>7309, 'province_id'=>73, 'name'=>'Pangkajene Dan Kepulauan']);
        $this->insert('ref_city', ['id'=>7310, 'province_id'=>73, 'name'=>'Barru']);
        $this->insert('ref_city', ['id'=>7311, 'province_id'=>73, 'name'=>'Bone']);
        $this->insert('ref_city', ['id'=>7312, 'province_id'=>73, 'name'=>'Soppeng']);
        $this->insert('ref_city', ['id'=>7313, 'province_id'=>73, 'name'=>'Wajo']);
        $this->insert('ref_city', ['id'=>7314, 'province_id'=>73, 'name'=>'Sidenreng Rappang']);
        $this->insert('ref_city', ['id'=>7315, 'province_id'=>73, 'name'=>'Pinrang']);
        $this->insert('ref_city', ['id'=>7316, 'province_id'=>73, 'name'=>'Enrekang']);
        $this->insert('ref_city', ['id'=>7317, 'province_id'=>73, 'name'=>'Luwu']);
        $this->insert('ref_city', ['id'=>7318, 'province_id'=>73, 'name'=>'Tana Toraja']);
        $this->insert('ref_city', ['id'=>7322, 'province_id'=>73, 'name'=>'Luwu Utara']);
        $this->insert('ref_city', ['id'=>7325, 'province_id'=>73, 'name'=>'Luwu Timur']);
        $this->insert('ref_city', ['id'=>7326, 'province_id'=>73, 'name'=>'Toraja Utara']);
        $this->insert('ref_city', ['id'=>7371, 'province_id'=>73, 'name'=>'Kota Makassar']);
        $this->insert('ref_city', ['id'=>7372, 'province_id'=>73, 'name'=>'Kota Parepare']);
        $this->insert('ref_city', ['id'=>7373, 'province_id'=>73, 'name'=>'Kota Palopo']);
        $this->insert('ref_city', ['id'=>7401, 'province_id'=>74, 'name'=>'Buton']);
        $this->insert('ref_city', ['id'=>7402, 'province_id'=>74, 'name'=>'Muna']);
        $this->insert('ref_city', ['id'=>7403, 'province_id'=>74, 'name'=>'Konawe']);
        $this->insert('ref_city', ['id'=>7404, 'province_id'=>74, 'name'=>'Kolaka']);
        $this->insert('ref_city', ['id'=>7405, 'province_id'=>74, 'name'=>'Konawe Selatan']);
        $this->insert('ref_city', ['id'=>7406, 'province_id'=>74, 'name'=>'Bombana']);
        $this->insert('ref_city', ['id'=>7407, 'province_id'=>74, 'name'=>'Wakatobi']);
        $this->insert('ref_city', ['id'=>7408, 'province_id'=>74, 'name'=>'Kolaka Utara']);
        $this->insert('ref_city', ['id'=>7409, 'province_id'=>74, 'name'=>'Buton Utara']);
        $this->insert('ref_city', ['id'=>7410, 'province_id'=>74, 'name'=>'Konawe Utara']);
        $this->insert('ref_city', ['id'=>7471, 'province_id'=>74, 'name'=>'Kota Kendari']);
        $this->insert('ref_city', ['id'=>7472, 'province_id'=>74, 'name'=>'Kota Baubau']);
        $this->insert('ref_city', ['id'=>7501, 'province_id'=>75, 'name'=>'Boalemo']);
        $this->insert('ref_city', ['id'=>7502, 'province_id'=>75, 'name'=>'Gorontalo']);
        $this->insert('ref_city', ['id'=>7503, 'province_id'=>75, 'name'=>'Pohuwato']);
        $this->insert('ref_city', ['id'=>7504, 'province_id'=>75, 'name'=>'Bone Bolango']);
        $this->insert('ref_city', ['id'=>7505, 'province_id'=>75, 'name'=>'Gorontalo Utara']);
        $this->insert('ref_city', ['id'=>7571, 'province_id'=>75, 'name'=>'Kota Gorontalo']);
        $this->insert('ref_city', ['id'=>7601, 'province_id'=>76, 'name'=>'Majene']);
        $this->insert('ref_city', ['id'=>7602, 'province_id'=>76, 'name'=>'Polewali Mandar']);
        $this->insert('ref_city', ['id'=>7603, 'province_id'=>76, 'name'=>'Mamasa']);
        $this->insert('ref_city', ['id'=>7604, 'province_id'=>76, 'name'=>'Mamuju']);
        $this->insert('ref_city', ['id'=>7605, 'province_id'=>76, 'name'=>'Mamuju Utara']);
        $this->insert('ref_city', ['id'=>8101, 'province_id'=>81, 'name'=>'Maluku Tenggara Barat']);
        $this->insert('ref_city', ['id'=>8102, 'province_id'=>81, 'name'=>'Maluku Tenggara']);
        $this->insert('ref_city', ['id'=>8103, 'province_id'=>81, 'name'=>'Maluku Tengah']);
        $this->insert('ref_city', ['id'=>8104, 'province_id'=>81, 'name'=>'Buru']);
        $this->insert('ref_city', ['id'=>8105, 'province_id'=>81, 'name'=>'Kepulauan Aru']);
        $this->insert('ref_city', ['id'=>8106, 'province_id'=>81, 'name'=>'Seram Bagian Barat']);
        $this->insert('ref_city', ['id'=>8107, 'province_id'=>81, 'name'=>'Seram Bagian Timur']);
        $this->insert('ref_city', ['id'=>8108, 'province_id'=>81, 'name'=>'Maluku Barat Daya']);
        $this->insert('ref_city', ['id'=>8109, 'province_id'=>81, 'name'=>'Buru Selatan']);
        $this->insert('ref_city', ['id'=>8171, 'province_id'=>81, 'name'=>'Kota Ambon']);
        $this->insert('ref_city', ['id'=>8172, 'province_id'=>81, 'name'=>'Kota Tual']);
        $this->insert('ref_city', ['id'=>8201, 'province_id'=>82, 'name'=>'Halmahera Barat']);
        $this->insert('ref_city', ['id'=>8202, 'province_id'=>82, 'name'=>'Halmahera Tengah']);
        $this->insert('ref_city', ['id'=>8203, 'province_id'=>82, 'name'=>'Kepulauan Sula']);
        $this->insert('ref_city', ['id'=>8204, 'province_id'=>82, 'name'=>'Halmahera Selatan']);
        $this->insert('ref_city', ['id'=>8205, 'province_id'=>82, 'name'=>'Halmahera Utara']);
        $this->insert('ref_city', ['id'=>8206, 'province_id'=>82, 'name'=>'Halmahera Timur']);
        $this->insert('ref_city', ['id'=>8207, 'province_id'=>82, 'name'=>'Pulau Morotai']);
        $this->insert('ref_city', ['id'=>8271, 'province_id'=>82, 'name'=>'Kota Ternate']);
        $this->insert('ref_city', ['id'=>8272, 'province_id'=>82, 'name'=>'Kota Tidore Kepulauan']);
        $this->insert('ref_city', ['id'=>9101, 'province_id'=>91, 'name'=>'Fakfak']);
        $this->insert('ref_city', ['id'=>9102, 'province_id'=>91, 'name'=>'Kaimana']);
        $this->insert('ref_city', ['id'=>9103, 'province_id'=>91, 'name'=>'Teluk Wondama']);
        $this->insert('ref_city', ['id'=>9104, 'province_id'=>91, 'name'=>'Teluk Bintuni']);
        $this->insert('ref_city', ['id'=>9105, 'province_id'=>91, 'name'=>'Manokwari']);
        $this->insert('ref_city', ['id'=>9106, 'province_id'=>91, 'name'=>'Sorong Selatan']);
        $this->insert('ref_city', ['id'=>9107, 'province_id'=>91, 'name'=>'Sorong']);
        $this->insert('ref_city', ['id'=>9108, 'province_id'=>91, 'name'=>'Raja Ampat']);
        $this->insert('ref_city', ['id'=>9109, 'province_id'=>91, 'name'=>'Tambrauw']);
        $this->insert('ref_city', ['id'=>9110, 'province_id'=>91, 'name'=>'Maybrat']);
        $this->insert('ref_city', ['id'=>9171, 'province_id'=>91, 'name'=>'Kota Sorong']);
        $this->insert('ref_city', ['id'=>9401, 'province_id'=>94, 'name'=>'Merauke']);
        $this->insert('ref_city', ['id'=>9402, 'province_id'=>94, 'name'=>'Jayawijaya']);
        $this->insert('ref_city', ['id'=>9403, 'province_id'=>94, 'name'=>'Jayapura']);
        $this->insert('ref_city', ['id'=>9404, 'province_id'=>94, 'name'=>'Nabire']);
        $this->insert('ref_city', ['id'=>9408, 'province_id'=>94, 'name'=>'Kepulauan Yapen']);
        $this->insert('ref_city', ['id'=>9409, 'province_id'=>94, 'name'=>'Biak Numfor']);
        $this->insert('ref_city', ['id'=>9410, 'province_id'=>94, 'name'=>'Paniai']);
        $this->insert('ref_city', ['id'=>9411, 'province_id'=>94, 'name'=>'Puncak Jaya']);
        $this->insert('ref_city', ['id'=>9412, 'province_id'=>94, 'name'=>'Mimika']);
        $this->insert('ref_city', ['id'=>9413, 'province_id'=>94, 'name'=>'Boven Digoel']);
        $this->insert('ref_city', ['id'=>9414, 'province_id'=>94, 'name'=>'Mappi']);
        $this->insert('ref_city', ['id'=>9415, 'province_id'=>94, 'name'=>'Asmat']);
        $this->insert('ref_city', ['id'=>9416, 'province_id'=>94, 'name'=>'Yahukimo']);
        $this->insert('ref_city', ['id'=>9417, 'province_id'=>94, 'name'=>'Pegunungan Bintang']);
        $this->insert('ref_city', ['id'=>9418, 'province_id'=>94, 'name'=>'Tolikara']);
        $this->insert('ref_city', ['id'=>9419, 'province_id'=>94, 'name'=>'Sarmi']);
        $this->insert('ref_city', ['id'=>9420, 'province_id'=>94, 'name'=>'Keerom']);
        $this->insert('ref_city', ['id'=>9426, 'province_id'=>94, 'name'=>'Waropen']);
        $this->insert('ref_city', ['id'=>9427, 'province_id'=>94, 'name'=>'Supiori']);
        $this->insert('ref_city', ['id'=>9428, 'province_id'=>94, 'name'=>'Mamberamo Raya']);
        $this->insert('ref_city', ['id'=>9429, 'province_id'=>94, 'name'=>'Nduga']);
        $this->insert('ref_city', ['id'=>9430, 'province_id'=>94, 'name'=>'Lanny Jaya']);
        $this->insert('ref_city', ['id'=>9431, 'province_id'=>94, 'name'=>'Mamberamo Tengah']);
        $this->insert('ref_city', ['id'=>9432, 'province_id'=>94, 'name'=>'Yalimo']);
        $this->insert('ref_city', ['id'=>9433, 'province_id'=>94, 'name'=>'Puncak']);
        $this->insert('ref_city', ['id'=>9434, 'province_id'=>94, 'name'=>'Dogiyai']);
        $this->insert('ref_city', ['id'=>9435, 'province_id'=>94, 'name'=>'Intan Jaya']);
        $this->insert('ref_city', ['id'=>9436, 'province_id'=>94, 'name'=>'Deiyai']);
        $this->insert('ref_city', ['id'=>9471, 'province_id'=>94, 'name'=>'Kota Jayapura']);


    }

    public function down()
    {
        echo "m150705_213801_create_city_table cannot be reverted.\n";

        return false;
    }
    
    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }
    
    public function safeDown()
    {
    }
    */
}
